// Code generated by goctl. DO NOT EDIT.
package types

type ProvinceCustomReq struct {
	Proname string `path:"proname"`
}

type ProvinceCustomReply struct {
	Customname string `json:"customname"`
	Count      string `json:"count"`
}

type CommonReq struct {
	Ddcode string `path:"ddcode"`
}

type CustomSummaryReply struct {
	Factoryname                string  `json:"factoryname"`
	Top100Sum                  float64 `json:"top100Sum"`
	CurrentMonthNewCustomCount float64 `json:"currentMonthNewCustomCount"`
	CurrentYearCustomCount     float64 `json:"currentYearCustomCount"`
}

type GoodsqtySummaryReply struct {
	CustomData   float64 `json:"customData"`
	FactoryData  float64 `json:"factoryData"`
	LevelOneData float64 `json:"levelOneData"`
}

type HsInfoReq struct {
	Id int64 `path:"id"`
}

type HsInfoReply struct {
	Id          int64  `json:"id"`
	Dataid      int64  `json:"dataid"`
	Factoryname string `json:"factoryname"`
}

type SettleSummaryReq struct {
}

type SettleSummaryReply struct {
	SettleSummaryByType []*SettleSummaryByTypeReply `json:"settlesummarybytype"`
	SettleSum           SettleSumReply              `json:"settlesum"`
}

type SettleSummaryByTypeReply struct {
	Typename   string `json:"typename"`
	Totalmoney string `json:"totalmoney"`
}

type SettleSumReply struct {
	Totalmoney string `json:"totalmoney"`
}
