// Code generated by goctl. DO NOT EDIT!
// Source: settle.ptoto

package server

import (
	"context"

	"ayzy_platform/service/settle/rpc/internal/logic"
	"ayzy_platform/service/settle/rpc/internal/svc"
	"ayzy_platform/service/settle/rpc/types/settle"
)

type SettleRpcServiceServer struct {
	svcCtx *svc.ServiceContext
	settle.UnimplementedSettleRpcServiceServer
}

func NewSettleRpcServiceServer(svcCtx *svc.ServiceContext) *SettleRpcServiceServer {
	return &SettleRpcServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *SettleRpcServiceServer) GetSummaryBySettleType(ctx context.Context, in *settle.SettleTypeSummaryRequest) (*settle.SettleTypeSummaryListResponse, error) {
	l := logic.NewGetSummaryBySettleTypeLogic(ctx, s.svcCtx)
	return l.GetSummaryBySettleType(in)
}

func (s *SettleRpcServiceServer) GetSum(ctx context.Context, in *settle.SettleCommonRequest) (*settle.SettleSumResponse, error) {
	l := logic.NewGetSumLogic(ctx, s.svcCtx)
	return l.GetSum(in)
}
