// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: settle.ptoto

package settle

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SettleCommonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SettleCommonRequest) Reset() {
	*x = SettleCommonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_settle_ptoto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SettleCommonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleCommonRequest) ProtoMessage() {}

func (x *SettleCommonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settle_ptoto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleCommonRequest.ProtoReflect.Descriptor instead.
func (*SettleCommonRequest) Descriptor() ([]byte, []int) {
	return file_settle_ptoto_rawDescGZIP(), []int{0}
}

type SettleTypeSummaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SettleTypeSummaryRequest) Reset() {
	*x = SettleTypeSummaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_settle_ptoto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SettleTypeSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleTypeSummaryRequest) ProtoMessage() {}

func (x *SettleTypeSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settle_ptoto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleTypeSummaryRequest.ProtoReflect.Descriptor instead.
func (*SettleTypeSummaryRequest) Descriptor() ([]byte, []int) {
	return file_settle_ptoto_rawDescGZIP(), []int{1}
}

type SettleTypeSummaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 结算类型名称
	Typename string `protobuf:"bytes,1,opt,name=typename,proto3" json:"typename,omitempty"`
	// 结算总额
	Totalmoney string `protobuf:"bytes,2,opt,name=totalmoney,proto3" json:"totalmoney,omitempty"`
}

func (x *SettleTypeSummaryResponse) Reset() {
	*x = SettleTypeSummaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_settle_ptoto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SettleTypeSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleTypeSummaryResponse) ProtoMessage() {}

func (x *SettleTypeSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settle_ptoto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleTypeSummaryResponse.ProtoReflect.Descriptor instead.
func (*SettleTypeSummaryResponse) Descriptor() ([]byte, []int) {
	return file_settle_ptoto_rawDescGZIP(), []int{2}
}

func (x *SettleTypeSummaryResponse) GetTypename() string {
	if x != nil {
		return x.Typename
	}
	return ""
}

func (x *SettleTypeSummaryResponse) GetTotalmoney() string {
	if x != nil {
		return x.Totalmoney
	}
	return ""
}

type SettleTypeSummaryListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*SettleTypeSummaryResponse `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *SettleTypeSummaryListResponse) Reset() {
	*x = SettleTypeSummaryListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_settle_ptoto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SettleTypeSummaryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleTypeSummaryListResponse) ProtoMessage() {}

func (x *SettleTypeSummaryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settle_ptoto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleTypeSummaryListResponse.ProtoReflect.Descriptor instead.
func (*SettleTypeSummaryListResponse) Descriptor() ([]byte, []int) {
	return file_settle_ptoto_rawDescGZIP(), []int{3}
}

func (x *SettleTypeSummaryListResponse) GetList() []*SettleTypeSummaryResponse {
	if x != nil {
		return x.List
	}
	return nil
}

type SettleSumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 所有账单结算总额
	Totalmoney string `protobuf:"bytes,1,opt,name=totalmoney,proto3" json:"totalmoney,omitempty"`
}

func (x *SettleSumResponse) Reset() {
	*x = SettleSumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_settle_ptoto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SettleSumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleSumResponse) ProtoMessage() {}

func (x *SettleSumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settle_ptoto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleSumResponse.ProtoReflect.Descriptor instead.
func (*SettleSumResponse) Descriptor() ([]byte, []int) {
	return file_settle_ptoto_rawDescGZIP(), []int{4}
}

func (x *SettleSumResponse) GetTotalmoney() string {
	if x != nil {
		return x.Totalmoney
	}
	return ""
}

var File_settle_ptoto protoreflect.FileDescriptor

var file_settle_ptoto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x70, 0x74, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1a, 0x0a,
	0x18, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x57, 0x0a, 0x19, 0x53, 0x65, 0x74,
	0x74, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x79, 0x70, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x79, 0x70, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x6d, 0x6f, 0x6e, 0x65, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x6d, 0x6f, 0x6e,
	0x65, 0x79, 0x22, 0x56, 0x0a, 0x1d, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x74, 0x6c,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x33, 0x0a, 0x11, 0x53, 0x65,
	0x74, 0x74, 0x6c, 0x65, 0x53, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x32,
	0xb7, 0x01, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x70, 0x63, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x61, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x42, 0x79, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20,
	0x2e, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x25, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x53, 0x75,
	0x6d, 0x12, 0x1b, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x74, 0x6c,
	0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x53, 0x75,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x73,
	0x65, 0x74, 0x74, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_settle_ptoto_rawDescOnce sync.Once
	file_settle_ptoto_rawDescData = file_settle_ptoto_rawDesc
)

func file_settle_ptoto_rawDescGZIP() []byte {
	file_settle_ptoto_rawDescOnce.Do(func() {
		file_settle_ptoto_rawDescData = protoimpl.X.CompressGZIP(file_settle_ptoto_rawDescData)
	})
	return file_settle_ptoto_rawDescData
}

var file_settle_ptoto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_settle_ptoto_goTypes = []interface{}{
	(*SettleCommonRequest)(nil),           // 0: settle.SettleCommonRequest
	(*SettleTypeSummaryRequest)(nil),      // 1: settle.SettleTypeSummaryRequest
	(*SettleTypeSummaryResponse)(nil),     // 2: settle.SettleTypeSummaryResponse
	(*SettleTypeSummaryListResponse)(nil), // 3: settle.SettleTypeSummaryListResponse
	(*SettleSumResponse)(nil),             // 4: settle.SettleSumResponse
}
var file_settle_ptoto_depIdxs = []int32{
	2, // 0: settle.SettleTypeSummaryListResponse.list:type_name -> settle.SettleTypeSummaryResponse
	1, // 1: settle.SettleRpcService.GetSummaryBySettleType:input_type -> settle.SettleTypeSummaryRequest
	0, // 2: settle.SettleRpcService.GetSum:input_type -> settle.SettleCommonRequest
	3, // 3: settle.SettleRpcService.GetSummaryBySettleType:output_type -> settle.SettleTypeSummaryListResponse
	4, // 4: settle.SettleRpcService.GetSum:output_type -> settle.SettleSumResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_settle_ptoto_init() }
func file_settle_ptoto_init() {
	if File_settle_ptoto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_settle_ptoto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SettleCommonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_settle_ptoto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SettleTypeSummaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_settle_ptoto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SettleTypeSummaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_settle_ptoto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SettleTypeSummaryListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_settle_ptoto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SettleSumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_settle_ptoto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_settle_ptoto_goTypes,
		DependencyIndexes: file_settle_ptoto_depIdxs,
		MessageInfos:      file_settle_ptoto_msgTypes,
	}.Build()
	File_settle_ptoto = out.File
	file_settle_ptoto_rawDesc = nil
	file_settle_ptoto_goTypes = nil
	file_settle_ptoto_depIdxs = nil
}
